version: "3.9"

services:
  crypto-mesh-db:
    image: mongo:latest
    container_name: crypto-mesh-db
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  crypto-mesh-broker:
    image: rabbitmq:4.0-management
    container_name: crypto-mesh-broker
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    restart: unless-stopped

  crypto-mesh-api:
    build: .
    image: cryptomesh-api:latest
    container_name: crypto-mesh-api
    depends_on:
      - crypto-mesh-db
      - crypto-mesh-broker
    ports:
      - "${API_PORT}:19000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  mongo-data: