services:
  crypto-mesh-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  crypto-mesh-broker:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

volumes:
  mongo-data: